### ISSUE TITLE
Search doesn't work. Does this still work?

### ISSUE THREAD

**Issue by Nova1545** [arrufat/spotify-search-provider#2]
Found this today and have been unable to make it work. The results dont show in the search, nor does it prompt for spotify login
Using Gnome 40 and Ubuntu 21.1

**Comment by arrufat** [comment]
I've been using it every day, and it still works on Arch with GNOME 42.
Could you detail the installation steps you followed?
You need to prepend your search query with a `$` sign.
example:
```
$play seven nation army
```
```
$queue seven nation army
```
And if you omit the key word, it will default to enqueue:
```
$ seven nation army
```

I use a `$` sign to prevent all search queries from being forwarded to Spotify servers.

**Comment by Nova1545** [comment]
I followed the manual installation method from the readme
I also reloaded gnome after installing it (Alt+F2, r)

**Comment by Nova1545** [comment]
![image](https://user-images.githubusercontent.com/43554977/165217071-c3a96fc0-1e3d-4028-b1e5-470fb5cbe6fa.png)
Image of what I get when I type something in

**Comment by arrufat** [comment]
Can you check if the script is running in the background? Can you run it manually from the terminal and see if outputs something?
Also, have you tried logging out and in?

**Comment by Nova1545** [comment]
I have tried logging out and in (plus restarting). The search provider is also enabled in gnome's search settings

Running it from the terminal results in nothing happening
![image](https://user-images.githubusercontent.com/43554977/165351131-ecbaaefb-1c3f-47c4-9636-5166f83ab1da.png)
Using a tool called gnome-search-cli also yields nothing
![image](https://user-images.githubusercontent.com/43554977/165351169-ac920442-268e-4605-8ea5-722c63586582.png)


The script is indeed running
![image](https://user-images.githubusercontent.com/43554977/165350681-bc916319-b590-4d3f-8f63-e5100c1ea261.png)

It has also never prompted for Spotify authentication

**Comment by arrufat** [comment]
Does this file exist?
```
~/.cache/spotify-search-provider/.cache
```
Can you remove it?

**Comment by Nova1545** [comment]
~/.cache/spotify-search-provider does but there is no .cache file

**Comment by arrufat** [comment]
I am running out of ideas… I've just deleted the `.cache` file, killed the `python` process, restarted the shell, and typed a query on the shell, and I was prompted to authenticate again. After that, it works again.

**Comment by Nova1545** [comment]
I found the problem
I had a random docker container running that was using port 8888, killing this fixed the problem (Found the container running by dumb luck)
However: The logging page for spotify returned a error for a invalid callback url (I fixed this by using my own api client) but it 
![image](https://user-images.githubusercontent.com/43554977/165423095-6cae55e0-6d6c-4a4c-b247-b38b83dc94da.png)
seems that http://localhost:8888/callback isnt valid according to spotify

**Comment by arrufat** [comment]
Oh, so maybe I should change the port to something less likely to be used by other stuff

**Comment by Nova1545** [comment]
You could, not sure what is less likely to be used though

**Comment by Nova1545** [comment]
Gonna close this now. Still using it to this day!
