### ISSUE TITLE
Doesn't return any search results (anymore?) 

### ISSUE THREAD

**Issue by major-mayer** [arrufat/spotify-search-provider#3]
Hi,
this project sound like a great idea, but at least for me after installing the AUR package, there is nothing listed in the Gnome shell, whenever i search something.
I wasn't able to find any logs besides those in journalctl, but they seem not too helpful:
![grafik](https://github.com/arrufat/spotify-search-provider/assets/17907799/1a787e0c-dfb3-493d-85fc-6f624eb2544b)
Feel free to give me any advice, how I can provide better logs, to see what is going on.

**Comment by arrufat** [comment]
Sorry for the late reply. It definitely works still, I use it everyday. Did it ask you to log in?

**Comment by arrufat** [comment]
Ah, maybe try making a search "$ song title".
Queries are prepended with a dollar sign and a space to prevent every search to go to Spotify.

**Comment by major-mayer** [comment]
Ahh you are totally right, I just didn't know that i need to prefix song titles with a "$".
But then the Spotify authorization dialog popped up and now everything is working nicely :)
Thank you for your support and good work.
